[tool.ruff]
line-length = 88
target-version = "py311"

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
ignore_missing_imports = true
exclude = [
    "tests",
    "custom_components/ofoehn_poolpilot/config_flow.py",
]
